config/routes.rb
Rails.application.routes.draw do

   root 'apis#index'
    resources :apis
  get  'find_dup', to: 'finddups#new'
  post 'find_dup', to: 'finddups#result'

end

app/models/api.rb
class Api < ActiveRecord::Base
    
  validates   :email, presence: true, 
              uniqueness: {case_sensitive: false} 
    
  def self.update_request(api)
    api.number_request = api.number_request + 1
    api.save
  end
  
end

app/models/find_duplicated_words.rb
class FindDuplicatedWords

  attr_accessor :word_position, :code, :status 
  
  def initialize
    @word_position = Hash.new

  end
  
  def call(sentence)
    sentencearray = sentence.split(" ")
    grouped_words = sentencearray.group_by { |x| x }
    counted = grouped_words.each_with_object({}) { |(k,v), hash| hash[k] = v.count}
    duplicated = counted.select { |k,v|  v > 1}
    duplicated.each do |k,v|  
      arraydup = sentencearray.map {|x| x == k } 
      position = []
      indi = 0
      arraydup.each do |bol|
        position << indi if bol
        indi = indi + 1
      end
      @word_position[k] = position 
    end
  end
end

                        

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  def index
    @apis = Api.all
  end
  
  def new
    @api = Api.new
  end
  
  def create
    @api = Api.new(api_params)
    @api.key =  generar_key
    if @api.save
      flash[:success] = "El API KEY fue creado satisfactoriamente"
      redirect_to root_path
    else
      render 'new'
    end
    
  end

end

private

def api_params
  params.require(:api).permit(:email)
end

def generar_key
  require 'digest/md5'
  Digest::MD5.hexdigest(@api.email)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finddups_controller.rb
class FinddupsController < ApplicationController
  
  def new

  end
  
  def result
    if api_key
      @duplicated_words = FindDuplicatedWords.new
      @duplicated_words.call(params[:session][:sentence])
      @status = "success"
      @code = "200"
      Api.update_request(@api_key)
    else
      @status = "unauthorized"
      @code = "401"
    end
  end
end


private

  def api_key
    @api_key ||= Api.find_by_key(params[:session][:apikey])
  end


  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apis/index.html.erb
<H1 align = 'center'> Listado de APIS</H1>

<div class="container">
  <table class="table table-striped table table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th>Key</th>
        <th>Numero de request</th>
      </tr>
    </thead>
    <tbody>
      <% @apis.each do |api| %>
        <tr>
          <td> <%= api.email %></td>
          <td><%= api.key %></td>
          <td><%= api.number_request %></td>
        </tr>
      <%end %>
    </tbody>
  </table>
</div>
<div class="col-xs-5 col-xs-offset-5">
  <%= link_to 'Crear API', new_api_path %> | 
  <%= link_to 'Conseguir duplicados', find_dup_path %>
</div>

app/views/apis/new.html.erb
<H1 align = 'center'> Crear API</H1>

<div class='row'>
  <div class='col-xs-12'> 
    <!--  los parametros, como las clases, se pasan en un hash -->
    <%= form_for(@api, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label "E-Mail"  %>
        </div> 
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Correo electronico", autofocus: true %>
        </div>
      </div>
        
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">  
            <%= f.submit "Crear API KEY", class: 'btn btn-primary btn-lg' %> 
        </div>
      </div>
    <% end %>
    <div class="col-xs-5 col-xs-offset-5">
      [<%= link_to "Regresar a la lista de APIS" , root_path, class: "link" %>]
    </div>
  </div>
</div>

app/views/finddups/new.html.erb
<h1 align = 'center'> Conseguir duplicados</h1>

<%= form_for(:session, :html => {class: "form-horizontal", role: "form"}, url: find_dup_path) do |f|  %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label "API Key"  %>
    </div> 
    <div class="col-sm-4">
      <%= f.text_field :apikey, class: "form-control", placeholder: "Introducir el API KEY", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label "Frase"  %> <br/>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :sentence, class: "form-control", placeholder: "Introducir la frase que deseas validar" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">  
       <!-- si es un nuevo registro coloca el primer string, sino, el segundo -->
      <%= f.submit "Buscar repetidos", class: 'btn btn-primary btn-lg'%> 
    </div>
  </div>
<% end %>
<div class="col-xs-5 col-xs-offset-5">
  [<%= link_to "Regresar a la lista de APIS" , root_path, class: "link" %>]
</div>

app/views/finddups/result.html.erb
<h1 align= 'center'>Resultado</h1>

<h3 align='center'>Codigo: <%= @code %> </h3>
<h3 align='center'> Estatus: <%= @status %> </h3>


<% if @code == '200' %>
  <h3 align='center'> Palabras repetidas </h3>
  <div class="container">
    <table  class="table table-striped table table-bordered">
      <thead>
        <tr>
          <th>Palabra</th>
          <th>Posiciones en donde se encuentra</th>
        </tr>
      </thead>
      <tbody>
        <% @duplicated_words.word_position.each do |k, v| %>
          <tr>
            <td > <%= k %></td>
            <td ><%= v.join(",") %></td>
          </tr>
        <%end %>
      </tbody>
    </table>
  <div class="container">
<% end %>
<div class="col-xs-5 col-xs-offset-5">
  [<%= link_to "Regresar a la lista de APIS" , root_path, class: "link" %>]
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiKeys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>